- .github/workflows/build-and-publish-cosmwasm.yml
- .github/workflows/build-and-publish-javascore.yml
- README.md
- contracts/javascore/build.gradle
- contracts/javascore/example-dapps/dapp-multi-protocol/build.gradle
- contracts/javascore/example-dapps/dapp-simple/build.gradle
- contracts/javascore/test-lib/build.gradle
- contracts/javascore/xcall/build.gradle
> ci: add cosmwasm & javascore build pipeline and codecov badge

- Cargo.toml
- contracts/cosmwasm-vm/cw-xcall/Cargo.toml
- contracts/cosmwasm-vm/cw-xcall/src/contract.rs
- contracts/cosmwasm-vm/cw-xcall/src/lib.rs
- contracts/cosmwasm-vm/cw-xcall/tests/test_admin.rs
```bash
fix: update version on migrate
```
```bash
```
> fix: update version on migrate

- contracts/javascore/xcall/src/main/java/foundation/icon/xcall/CallService.java
- contracts/javascore/xcall/src/main/java/foundation/icon/xcall/CallServiceImpl.java
- docs/adr/xcall.md
> fix: Improve parameter consistency in xCall java and spec

- .github/workflows/release-tag-manager.yml
> ci: add manual cicd job to push release tag

- contracts/cosmwasm-vm/cw-xcall/src/assertion.rs
- contracts/cosmwasm-vm/cw-xcall/src/connection.rs
- contracts/cosmwasm-vm/cw-xcall/src/execute_call.rs
- contracts/cosmwasm-vm/cw-xcall/src/handle_call_message.rs
- contracts/cosmwasm-vm/cw-xcall/src/lib.rs
- contracts/cosmwasm-vm/cw-xcall/src/send_call_message.rs
- contracts/cosmwasm-vm/cw-xcall/src/state.rs
- contracts/cosmwasm-vm/cw-xcall/src/types/message.rs
- contracts/cosmwasm-vm/cw-xcall/src/types/mod.rs
- contracts/cosmwasm-vm/cw-xcall/src/types/request.rs
- contracts/cosmwasm-vm/cw-xcall/src/types/response.rs
- contracts/cosmwasm-vm/cw-xcall/tests/test_handle_call_message.rs
> fix: struct naming according to docs

- contracts/cosmwasm-vm/cw-xcall/src/connection.rs
- contracts/cosmwasm-vm/cw-xcall/src/contract.rs
- contracts/cosmwasm-vm/cw-xcall/src/dapp.rs
- contracts/cosmwasm-vm/cw-xcall/src/execute_rollback.rs
- contracts/cosmwasm-vm/cw-xcall/src/send_call_message.rs
> fix: reply removed from sendcallmessage and executerollback

- contracts/cosmwasm-vm/cw-xcall/src/lib.rs
```bash
fix: not feature library added in instantiate
```
```bash
```
> fix: not feature library added in instantiate

- contracts/cosmwasm-vm/cw-xcall/src/dapp.rs
- contracts/cosmwasm-vm/cw-xcall/src/execute_rollback.rs
- contracts/cosmwasm-vm/cw-xcall/src/lib.rs
- contracts/cosmwasm-vm/cw-xcall/tests/test_admin.rs
- scripts/optimize-cosmwasm.sh
- scripts/optimize-jar.sh
```bash
fix: e2e and integration test cleanup
```
```bash
```
> fix: e2e and integration test

- contracts/cosmwasm-vm/cw-xcall/src/fees.rs
- contracts/cosmwasm-vm/cw-xcall/src/send_call_message.rs
- contracts/cosmwasm-vm/cw-xcall/tests/test_call_message.rs
```bash
fix: fee check send message
```
```bash
```
> fix: fee check send message

- contracts/evm/xcall/contracts/CallService.sol
- Add setDefaultConnection() with adminGuard
- Add revertMessages on `require()`
```bash
```
```bash
```
> fix: add default connection setter

- contracts/evm/xcall/contracts/CallService.sol
- contracts/evm/xcall/test/CallService.t.sol
> feat: handle requests multiple testcases

- contracts/evm/xcall/README.md
```bash
type: update xcall-solidity document
```
```bash
```
> docs: solidity xcall deployment

- .github/workflows/release.yml
```bash
ci: enable release in github release action
```
```bash
```
> ci: enable release in an action

- .github/workflows/solidity-contracts-test.yml
- .github/workflows/solidity-cov.yml
> feat: ci add solidity code coverages

- contracts/evm/library/utils/Types.sol
- contracts/evm/test/xcall/CallService.t.sol
- contracts/javascore/xcall-lib/src/main/java/foundation/icon/xcall/CallService.java
- contracts/javascore/xcall/src/test/java/foundation/icon/xcall/CallServiceTest.java
- docs/adr/xcall.md
> feat: Change xcall btp service name to xcallM

- Cargo.toml
- contracts/javascore/xcall/build.gradle
> ci: bump version of xcall-multi to 0.1.1

- scripts/optimize-cosmwasm.sh
```bash
ix: use constant version of cosmwasm-check@1.4.1 for build
```
```bash
```
> fix: use constant version of cosmwasm-check@1.4.1 for build

- contracts/cosmwasm-vm/cw-xcall/src/handle_call_message.rs
- contracts/cosmwasm-vm/cw-xcall/tests/test_request.rs
> fix: Prevent networkId to be from native chain when receiving call messsages.

- contracts/cosmwasm-vm/cw-xcall/src/contract.rs
- contracts/cosmwasm-vm/cw-xcall/src/lib.rs
```bash
fix: update network id
```
```bash
```
> fix: fix networkid

- docs/adr/xcall.md
> docs: Add new message structure to xCall design doc

- contracts/evm/contracts/adapters/CentralizedConnection.sol
- contracts/javascore/centralized-connection/src/main/java/xcall/adapter/centralized/CentralizedConnection.java
```bash
fix: architecture updated
```
```bash
```
> fix: architecture updated

- contracts/javascore/xcall-lib/src/main/java/foundation/icon/xcall/messages/PersistentMessage.java
- contracts/javascore/xcall/src/main/java/foundation/icon/xcall/CallServiceImpl.java
- contracts/javascore/xcall/src/test/java/foundation/icon/xcall/CallServiceTest.java
- docs/adr/xcall.md
> feat: Implement persistent message type in Java

- contracts/javascore/xcall-lib/src/main/java/foundation/icon/xcall/CSMessageRequest.java
- contracts/javascore/xcall-lib/src/main/java/foundation/icon/xcall/CSMessageResult.java
- contracts/javascore/xcall/src/main/java/foundation/icon/xcall/CallServiceImpl.java
- contracts/javascore/xcall/src/test/java/foundation/icon/xcall/CallServiceTest.java
> feat: Implement reply for two way messages

- contracts/javascore/example-dapps/dapp-multi-protocol/src/main/java/xcall/sample/dapp/MultiProtocolSampleDapp.java
- contracts/javascore/example-dapps/dapp-simple/src/main/java/xcall/sample/dapp/SimpleDapp.java
- contracts/javascore/xcall/src/main/java/foundation/icon/xcall/CallServiceImpl.java
```bash
feat: javascore dapp new message type
```
```bash
```
> feat: javascore dapp new message type

- contracts/evm/contracts/xcall/CallService.sol
```bash
fix: optimized in claimProtocolFee
```
```bash
```
> fix: optimized in claimProtocolFee

- contracts/evm/contracts/xcall/CallService.sol
```bash
fix: readability in compare string
```
```bash
```
> fix: readability in compare string

- contracts/evm/README.md
- docs/centralized-connection-setup.md
- docs/centralized-connection.md
> docs: clearer centralized deployment

- contracts/cosmwasm-vm/cw-integration/tests/test_xcall.rs
- contracts/cosmwasm-vm/cw-xcall/src/execute_call.rs
- contracts/cosmwasm-vm/cw-xcall/tests/test_handle_call_message.rs
- contracts/javascore/xcall/src/main/java/foundation/icon/xcall/CallServiceImpl.java
- contracts/javascore/xcall/src/test/java/foundation/icon/xcall/CallServiceTest.java
When receiving CallMessage results from cosmwasm or EVM it is encoded as  empty array instead of null. So this adds handling for when it is a empty array as well.
```bash
```
```bash
```
> fix: Add support for non null reply encoding

- contracts/cosmwasm-vm/cw-centralized-connection/src/contract.rs
changes made
- fixed storing same connection sequence for two times when sending message
> fix: remove duplicate store connection message sequence

- contracts/sui/xcall/sources/centralized_connection/centralized_entry.move
- contracts/sui/xcall/sources/centralized_connection/centralized_state.move
```bash
fix: bug fixes in sui xcall
```
```bash
```
> fix: bug fixes in sui xcall

- contracts/evm/contracts/xcall/CallService.sol
…col verification
```bash
```
```bash
```
> fix: Use msgPayload hash instead of request data hash for multi protocol verification

- contracts/sui/xcall/sources/main.move
```bash
fix: message field added in rollback event
```
```bash
```
> fix: message field added in rollback event

- .github/workflows/basic-rust.yml
- .github/workflows/cosmwasm-contracts-code-coverage.yml
- .gitmodules
- contracts/cosmwasm-vm/cw-xcall/src/handle_call_message.rs
- contracts/cosmwasm-vm/cw-xcall/src/types/request.rs
```bash
fix: patch valid source check
```
```bash
```
> fix: patch valid source check

- contracts/sui/xcall/sources/centralized_connection/centralized_connection.move
```bash
fix: relayer fees in response
```
```bash
```
> fix: relayer fees in response

- contracts/evm/contracts/xcall/CallService.sol
```bash
fix: call executed event added in persistent type
```
```bash
```
> fix: call executed event added in persistent type

- contracts/soroban/contracts/centralized-connection/src/contract.rs
- contracts/soroban/contracts/centralized-connection/src/storage.rs
- contracts/soroban/contracts/centralized-connection/src/types.rs
- contracts/soroban/libs/soroban-rlp/src/test/encoder.rs
- contracts/soroban/libs/soroban-rlp/src/test/utils.rs
- contracts/soroban/libs/soroban-rlp/src/utils.rs
> fix: add zero prefix for numeric types

- contracts/sui/libs/sui_rlp/sources/decoder.move
- contracts/sui/libs/sui_rlp/sources/encoder.move
- contracts/sui/libs/sui_rlp/sources/utils.move
- contracts/sui/libs/sui_rlp/tests/rlp_tests.move
> fix: sui eth-rlp fixes

- contracts/evm/test/adapters/ClusterConnection.t.sol
```bash
fix: cluster connection test fix
```
```bash
```
> fix: cluster connection test fix

- contracts/sui/libs/sui_rlp/sources/encoder.move
- contracts/sui/libs/sui_rlp/sources/utils.move
```bash
fix: sui rlp upgrade
```
```bash
```
> fix: sui rlp upgrade

- .github/workflows/build-and-publish-cosmwasm.yml
- .github/workflows/build-and-publish-javascore.yml
- .github/workflows/codecov-javascore.yml
- .github/workflows/cosmwasm-contracts-code-coverage.yml
- .github/workflows/deploy-cosmwasm-contracts.yml
- .github/workflows/java-contracts-test.yml
- .github/workflows/publish_maven.yml
- .github/workflows/release-tag-manager.yml
- .github/workflows/release.yml
- .github/workflows/solidity-contracts-test.yml
- .github/workflows/solidity-cov.yml
- .github/workflows/stellar-build-and-test.yml
- .github/workflows/sui-move-build-test.yml
- .github/workflows/uat-deploy-java-contracts.yml
> ci: update deprecated action version

- contracts/evm/contracts/adapters/ClusterConnection.sol
- contracts/evm/library/xcall/utils/Strings.sol
- contracts/evm/test/adapters/ClusterConnection.t.sol
- contracts/javascore/cluster-connection/src/main/java/xcall/adapter/cluster/ClusterConnection.java
- contracts/javascore/cluster-connection/src/test/java/xcall/adapter/cluster/ClusterConnectionTest.java
- contracts/javascore/xcall-lib/src/main/java/foundation/icon/xcall/CallService.java
> fix: cluster connection audit

- contracts/soroban/Cargo.lock
- contracts/soroban/contracts/multisig/Cargo.toml
- contracts/soroban/contracts/multisig/Readme.md
- contracts/soroban/contracts/multisig/src/lib.rs
- contracts/soroban/contracts/multisig/src/states.rs
```bash
feat: stellar multisig
```
```bash
```
> feat: stellar multisig

- contracts/solana/programs/cluster-connection/src/helper.rs
- contracts/solana/programs/cluster-connection/src/state.rs
```bash
fix: solana cluster connection
```
```bash
```
> fix: solana cluster connection
